apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}
spec:
  type: ClusterIP
  selector:
    app: {{APP_NAME}}
  ports:
  - port: 8125
    targetPort: 8125
    protocol: UDP
  - port: 8188
    targetPort: 8125
    protocol: UDP
